### PR TITLE
moved some files and added some stuff to a new site templates section…

### PR DESCRIPTION
**Pull request by tomjn**
…, simplified the add new site page, moved the zip to git conversion instructions to a newpage, updated section titles

### CODE REVIEW

**Comment by tomjn** [comment]
Closes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1410
Closes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1416

**Review by cagross — COMMENTED** [review]
Here are my comments:

* docs/en-US/adding-a-new-site/changing-php-version.md:  I have never encountered these instructions, so I will refrain from commenting on your edits.

* docs/en-US/adding-a-new-site/index.md:  

The paring down of these instructions, as you did, makes them much simpler and easier to follow.  The removing of extraneous steps (e.g. creating provision files) contributes to its increased simplicity.

--Line 11:  For me, this line could be improved slightly. 
 For readers that don't have much experience with .yml files (like myself), I wouldn't mind explicitly telling them that we are going to add new lines to `vvv-custom.yml`, e.g.:

First we need to tell VVV about the site.  I'm going to give the site the name `example`, with the URL `example.test`, using the custom site template, and update the sites list.  To do this, I will add the following lines to `vvv-custom.yml`:

More importantly though, had I read these instructions (i.e. Line 11) 24 hours ago, I would have been confused by the phrase, "...using the custom site template..."  Until yesterday, I had never heard that term, and I only have an idea about it now because of your guidance yesterday (thank you).  Would it be accurate to say that "...using the custom site template..." implies that the new site will be created using the latest WordPress build?  If so, then I think it might be beneficial to explain that here.  If that is not accurate, I apologize--you can see that I'm still not 100% on the term's meaning and implication here.  I only know that when I setup my site using the 'custom site template,' it was created using the latest WordPress version.

--Line 20:  This is clear, and I think the added line about YAML indenting will be helpful.

--Line 26:  I think it might be helpful to explicitly note that, at this point during the instructions, a new working WordPress site has now been created at the URL in-question, with a blank database.  When I was stepping through the instructions the first time, it wasn't entirely obvious to me whether I needed to take an extra step to import/create a database, or if that had been done for me.  I saw from the output of `vagrant reload --provision` that a database had been created.  But it might be helpful to novices to explicitly state here:  you now have a fully functional website running WordPress at your new URL.  Maybe you can re-write line 26 as:

After ``vagrant reload --provision` has completed, your new WordPress site will be setup and accessible at example.test. The default WordPress credentials are username:  admin and password:  password.  At this point (if desired), mysql or PHPMyAdmin can be used to upload an existing database for content, and plugins/themes/uploads can be copied. The installation of WP will be in `www/example/public_html`, and a PHP error log will be located at `www/example/logs/`.

* docs/en-US/installation/converting-zip-install-to-git.md:  I have never encountered these instructions, so I will refrain from commenting on your edits.

* In /adding-a-new-site/nginx-configuration/ and /adding-a-new-site/setup-script/, it might be helpful to state that it is not necessary to manually add the two files in-question (`vvv-init.sh` and `vvv-nginx.conf`)--they are automatically generated for you if you follow the instructions in /adding-a-new-site/.  Correct me if that is inaccurate, but that is what I have in my notes.

That is all I have.  Hope that's not too harsh.  Let me know if you have any follow-up questions, comments, or concerns--I'm happy to help.

**Comment by tomjn** [comment]
Thanks for the review @cagross :) I've made some changes that should make things clearer based on the feedback

**Review by LoreleiAurora — APPROVED** [review]

**Comment by cagross** [comment]
No problem @tomjn--happy to do so.

**Pull request merged**
