### PR TITLE
Switch to the Edition theme

### PR DESCRIPTION
**Pull request by tomjn**
WIP PR, this switches the VVV site over to the Edition theme, here's what it currently looks like:

screen shot 2017-09-04 at 02 51 56

### CODE REVIEW

**Comment by tomjn** [comment]
the theme adds a sidebar navigation, and the means to categorise things, as well as realtime full text search of all docs in JS, and just generally being prettier

Todo:

 - replace apple touch icons
 - add a posts page
 - extra sweeps to cleanup pages, some done already
 - ordering the adding a new site etc pages
 - some doc pages don't seem to flow as well now they have a clear ordering
 - make travis pass

```
bundle install
bundle exec jekyll --serve
```

**Comment by tomjn** [comment]
vvv


@jeremyfelt for the favicon/social icons, the VVV ASCII doesn't work as well, it isn't as bright/legible enough at small sizes, I have this icon I was using for my React/Electon VVV test app if you'd like me to use it?

**Comment by tomjn** [comment]
I've set it up using GitHub Pages as an easy way to for people to test at:

https://tomjn.github.io/varyingvagrantvagrants.org/

**Comment by jeremyfelt** [comment]
I think I'm digging this. The vertical nav is very good. That icon is nice! 👍

I'll play around with it a bit more in the very near future.

**Comment by tomjn** [comment]
Right, I'm pretty much done here, just need to merge my changes back into the PR branch from `gh-pages` and correct the URL/base url

**Comment by tomjn** [comment]
I've a few documentation changes I'd like to make, but I'd prefer this to be merged in first, as this also makes changes so that it flows, as well as some corrections and rearrangement

**Review by LoreleiAurora — APPROVED** [review]
Pretty :)

**Pull request merged**
