### PR TITLE
Updates to What is VVV, Tideways, WP-CLI, Xdebug, and Software Requirements Docs

### PR DESCRIPTION
**Pull request by davidshq**
Enhancements to grammar/clarity in several documents.

Updated some requirements/links to match current requirements/links.

Removed reference to Vagrant Ubuntu root login, no longer applicable.

### CODE REVIEW

**Comment by Mte90** [comment]
I see only one change to a single document

**Comment by davidshq** [comment]
Weird. I'm guessing you are only seeing the update to default-credentials.md and not any of the others pictured below?
vvv-pull-request

**Comment by Mte90** [comment]
immagine

I see this and when I open Files changed there is only one line.

**Comment by davidshq** [comment]
Okay, I am seeing that too. Really weird.

The other eight files are ones I committed in the past and that were merged in, so I'm unsure why this pull request is adding them again...

**Comment by tomjn** [comment]
If your branch also contains those changesets, it won't matter as the diff shown here is just the final diff between the end of this branch and the end of the develop branch, I see all the commits but only 5 lines being removed in a file are what this PR would result in.

I'd suggest creating new PRs based off of the current  `master` branch, taking a more atomic approach to things than one big PR

**Comment by tomjn** [comment]
I remedied this with another commit that explains why you can't SSH in as `root`

**Pull request closed without merging**
